authorName: Jerry
experimentName: example_mnist_pytorch_with_trailNum
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 40
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: ss_useData161-scarFree-strainMat-fixedSpitbyPat.json
#choice: true, false
useAnnotation: false
logDir: C:\Users\remus\OneDrive\Documents\Study\Researches\Projects\cardiac\strainmat_to_tos\nni_logs
# logDir: ..\\nni_logs
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python main_nii.py
  codeDir: ..\\
  gpuNum: 1

